update

install ansible
install awscli
install bash-completion
install ctags
install curl-ca-bundle
install ffmpeg
install ghostscript
install gimp
install git
install graphviz
install heroku-toolbelt
install hub
install imagemagick
install libyaml
install mongodb
install mysql
install nkf
install openssl
install phantomjs
install pow
install postgres
install qt
install rbenv
install readline
install redis
install ruby-build
install terminal-notifier
install tig
install tree
install wget
install wkhtmltopdf

install homebrew/apache/httpd24
install homebrew/php/php56 --homebrew-apxs
