install bash-completion
install ctags
install curl-ca-bundle
install ffmpeg
install git
install graphviz
install hub
install imagemagick
install libyaml
install mongodb
install mysql
install nkf
install openssl
install phantomjs
install pow
install qt
install rbenv
install readline
install ruby-build
install tig
install tree
install wget
install wkhtmltopdf

install djl/apache2/apache24
install josegonzalez/php/php55 --homebrew-apxs
