brew "asdf"
brew "diff-pdf"
brew "ffmpeg"
brew 'git' # to enable git-completion.bash
brew "graphicsmagick"
brew "jq"
brew "mackup"
brew "mas"
brew "neovim"
brew "streamlink"
brew "tig"
brew "tree"
brew "wget"
brew "yt-dlp"

cask "appcleaner"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "grandperspective"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "libreoffice"
cask "microsoft-edge"
cask "obs"
cask "slack"
cask "steam"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

mas "LINE", id: 539883307
